jobs:
- job: Linux

  pool:
    vmImage: 'Ubuntu 16.04'

  variables:
    GOPATH: '$(system.defaultWorkingDirectory)'

  steps:
  - checkout: none
  - script: |
      go version
      go get -v -t -d v2ray.com/core/...
      go get -v -t -d v2ray.com/ext/...
    workingDirectory: '$(system.defaultWorkingDirectory)'
    displayName: 'Fetch sources'
  - script: |
      go test -p 1 -tags json -v v2ray.com/core/...
    workingDirectory: '$(system.defaultWorkingDirectory)'
    displayName: 'Test'

- job: Linux Coverage
  dependsOn: Linux

  pool:
    vmImage: 'Ubuntu 16.04'

  variables:
    GOPATH: '$(system.defaultWorkingDirectory)'

  steps:
  - checkout: none
  - script: |
      go version
      go get -v -t -d v2ray.com/core/...
      go get -v -t -d v2ray.com/ext/...
    workingDirectory: '$(system.defaultWorkingDirectory)'
    displayName: 'Fetch sources'
  - script: |
      cd ./src/v2ray.com/core
      bash ./testing/coverage/coverall
    workingDirectory: '$(system.defaultWorkingDirectory)'
    displayName: 'Coverage'

- job: MacOS

  pool:
    vmImage: 'macOS-10.13'

  variables:
    GOPATH: '$(system.defaultWorkingDirectory)'

  steps:
  - checkout: none
  - script: |
      go version
      go get -v -t -d v2ray.com/core/...
      go get -v -t -d v2ray.com/ext/...
    workingDirectory: '$(system.defaultWorkingDirectory)'
    displayName: 'Fetch sources'
  - script: |
      go test -p 1 -tags json -v v2ray.com/core/...
    workingDirectory: '$(system.defaultWorkingDirectory)'
    displayName: 'Test'

- job: Windows

  pool:
    vmImage: 'vs2017-win2016'

  variables:
    GOPATH: '$(system.defaultWorkingDirectory)'

  steps:
  - checkout: none
  - script: |
      go version
      go get -v -t -d v2ray.com/core/...
      go get -v -t -d v2ray.com/ext/...
    workingDirectory: '$(system.defaultWorkingDirectory)'
    displayName: 'Fetch sources'
  - script: |
      go test -p 1 -tags json -v v2ray.com/core/...
    workingDirectory: '$(system.defaultWorkingDirectory)'
    displayName: 'Test'
